### ISSUE TITLE
Please update the Image in the Readme file before the pre-requisites section

### ISSUE THREAD

**Issue by Raveendiran-RR** [kubetoolsca/krs#30]
The the  image before the per-requisites sections in the readme file leads to resource not found 

<img width="946" alt="image" src="https://github.com/kubetoolsca/krs/assets/46484439/5cce0ee6-e466-4039-972d-77caef06de40">

**Comment by Raveendiran-RR** [comment]
Readme page screenshot

![image](https://github.com/kubetoolsca/krs/assets/46484439/490dd6a8-c386-423d-b3fa-ce0525343895)

**Comment by ajeetraina** [comment]
@Raveendiran-RR I have fixed the URLs. That should work for you.

**Comment by ajeetraina** [comment]
Closing this issue.
