### ISSUE TITLE
Unable to find Local AI option under krs health

### ISSUE THREAD

**Issue by ajeetraina** [kubetoolsca/krs#64]
When I installed the latest version of Krs, I don't see Local AI option

```
krs health

Starting interactive terminal...


Choose the model provider for healthcheck:

[1] OpenAI
[2] Huggingface

>>
```

**Comment by ajeetraina** [comment]
Look like it is not still merged to main branch.

**Comment by ajeetraina** [comment]
It is not yet merged.

**Comment by karanveersingh5623** [comment]
@OluchukwuON , can you check again , LocalAI option and update

**Comment by OluchukwuON** [comment]
Hello,

Sorry for my late response.
But it's actually merged to the pre-release branch rather than the main.

From what I understand, I shouldn't make pull requests to the main branch,
hence my actions stopped after the merge to pre-release.

Warm regards,
Oluchukwu.
